"A four-hour depression nap."
"A live studio audience."
"Joyless, wooden soviet toys."
"Being able to talk to elephants."
"A good bra."
"A disappointing birthday party."
"Boy that looks swollen."
"Lotion."
"Therapy."
"Slightly pathetic."
"A toothless woman gumming on a peach."
"Free samples."

