"A four-hour depression nap."
"A live studio audience."
"Joyless, wooden soviet toys."
"Thong crust."
"Being able to talk to elephants."
"A good bra."
"Burgers and pussy."
"A disappointing birthday party."
"One titty hanging out."
"An endless pee."
"Boy that looks swollen."
"Lotion."
"Therapy."
"Slightly pathetic."
"Incest."
"A toothless woman gumming on a peach."
"Free samples."

